-- Seed English country names (name_en field)
-- Run this script to populate English translations for all countries

BEGIN;

UPDATE countries SET name_en = 'Andorra' WHERE code = 'AD';
UPDATE countries SET name_en = 'United Arab Emirates' WHERE code = 'AE';
UPDATE countries SET name_en = 'Afghanistan' WHERE code = 'AF';
UPDATE countries SET name_en = 'Antigua and Barbuda' WHERE code = 'AG';
UPDATE countries SET name_en = 'Albania' WHERE code = 'AL';
UPDATE countries SET name_en = 'Armenia' WHERE code = 'AM';
UPDATE countries SET name_en = 'Angola' WHERE code = 'AO';
UPDATE countries SET name_en = 'Argentina' WHERE code = 'AR';
UPDATE countries SET name_en = 'American Samoa' WHERE code = 'AS';
UPDATE countries SET name_en = 'Austria' WHERE code = 'AT';
UPDATE countries SET name_en = 'Australia' WHERE code = 'AU';
UPDATE countries SET name_en = 'Aruba' WHERE code = 'AW';
UPDATE countries SET name_en = 'Azerbaijan' WHERE code = 'AZ';
UPDATE countries SET name_en = 'Bosnia and Herzegovina' WHERE code = 'BA';
UPDATE countries SET name_en = 'Barbados' WHERE code = 'BB';
UPDATE countries SET name_en = 'Bangladesh' WHERE code = 'BD';
UPDATE countries SET name_en = 'Belgium' WHERE code = 'BE';
UPDATE countries SET name_en = 'Burkina Faso' WHERE code = 'BF';
UPDATE countries SET name_en = 'Bulgaria' WHERE code = 'BG';
UPDATE countries SET name_en = 'Bahrain' WHERE code = 'BH';
UPDATE countries SET name_en = 'Burundi' WHERE code = 'BI';
UPDATE countries SET name_en = 'Benin' WHERE code = 'BJ';
UPDATE countries SET name_en = 'Bermuda' WHERE code = 'BM';
UPDATE countries SET name_en = 'Brunei' WHERE code = 'BN';
UPDATE countries SET name_en = 'Bolivia' WHERE code = 'BO';
UPDATE countries SET name_en = 'Brazil' WHERE code = 'BR';
UPDATE countries SET name_en = 'Bahamas' WHERE code = 'BS';
UPDATE countries SET name_en = 'Bhutan' WHERE code = 'BT';
UPDATE countries SET name_en = 'Botswana' WHERE code = 'BW';
UPDATE countries SET name_en = 'Belarus' WHERE code = 'BY';
UPDATE countries SET name_en = 'Belize' WHERE code = 'BZ';
UPDATE countries SET name_en = 'Canada' WHERE code = 'CA';
UPDATE countries SET name_en = 'Democratic Republic of the Congo' WHERE code = 'CD';
UPDATE countries SET name_en = 'Congo' WHERE code = 'CG';
UPDATE countries SET name_en = 'Switzerland' WHERE code = 'CH';
UPDATE countries SET name_en = 'Ivory Coast' WHERE code = 'CI';
UPDATE countries SET name_en = 'Chile' WHERE code = 'CL';
UPDATE countries SET name_en = 'Cameroon' WHERE code = 'CM';
UPDATE countries SET name_en = 'China' WHERE code = 'CN';
UPDATE countries SET name_en = 'Colombia' WHERE code = 'CO';
UPDATE countries SET name_en = 'Costa Rica' WHERE code = 'CR';
UPDATE countries SET name_en = 'Cuba' WHERE code = 'CU';
UPDATE countries SET name_en = 'Cape Verde' WHERE code = 'CV';
UPDATE countries SET name_en = 'Curacao' WHERE code = 'CW';
UPDATE countries SET name_en = 'Cyprus' WHERE code = 'CY';
UPDATE countries SET name_en = 'Czech Republic' WHERE code = 'CZ';
UPDATE countries SET name_en = 'Germany' WHERE code = 'DE';
UPDATE countries SET name_en = 'Djibouti' WHERE code = 'DJ';
UPDATE countries SET name_en = 'Denmark' WHERE code = 'DK';
UPDATE countries SET name_en = 'Dominica' WHERE code = 'DM';
UPDATE countries SET name_en = 'Dominican Republic' WHERE code = 'DO';
UPDATE countries SET name_en = 'Algeria' WHERE code = 'DZ';
UPDATE countries SET name_en = 'Ecuador' WHERE code = 'EC';
UPDATE countries SET name_en = 'Estonia' WHERE code = 'EE';
UPDATE countries SET name_en = 'Egypt' WHERE code = 'EG';
UPDATE countries SET name_en = 'Eritrea' WHERE code = 'ER';
UPDATE countries SET name_en = 'Spain' WHERE code = 'ES';
UPDATE countries SET name_en = 'Ethiopia' WHERE code = 'ET';
UPDATE countries SET name_en = 'Finland' WHERE code = 'FI';
UPDATE countries SET name_en = 'Fiji' WHERE code = 'FJ';
UPDATE countries SET name_en = 'Micronesia' WHERE code = 'FM';
UPDATE countries SET name_en = 'Faroe Islands' WHERE code = 'FO';
UPDATE countries SET name_en = 'France' WHERE code = 'FR';
UPDATE countries SET name_en = 'Gabon' WHERE code = 'GA';
UPDATE countries SET name_en = 'United Kingdom' WHERE code = 'GB';
UPDATE countries SET name_en = 'Grenada' WHERE code = 'GD';
UPDATE countries SET name_en = 'Georgia' WHERE code = 'GE';
UPDATE countries SET name_en = 'French Guiana' WHERE code = 'GF';
UPDATE countries SET name_en = 'Guernsey' WHERE code = 'GG';
UPDATE countries SET name_en = 'Ghana' WHERE code = 'GH';
UPDATE countries SET name_en = 'Gibraltar' WHERE code = 'GI';
UPDATE countries SET name_en = 'Greenland' WHERE code = 'GL';
UPDATE countries SET name_en = 'Gambia' WHERE code = 'GM';
UPDATE countries SET name_en = 'Guinea' WHERE code = 'GN';
UPDATE countries SET name_en = 'Guadeloupe' WHERE code = 'GP';
UPDATE countries SET name_en = 'Equatorial Guinea' WHERE code = 'GQ';
UPDATE countries SET name_en = 'Greece' WHERE code = 'GR';
UPDATE countries SET name_en = 'Guatemala' WHERE code = 'GT';
UPDATE countries SET name_en = 'Guam' WHERE code = 'GU';
UPDATE countries SET name_en = 'Guinea-Bissau' WHERE code = 'GW';
UPDATE countries SET name_en = 'Guyana' WHERE code = 'GY';
UPDATE countries SET name_en = 'Hong Kong' WHERE code = 'HK';
UPDATE countries SET name_en = 'Honduras' WHERE code = 'HN';
UPDATE countries SET name_en = 'Croatia' WHERE code = 'HR';
UPDATE countries SET name_en = 'Haiti' WHERE code = 'HT';
UPDATE countries SET name_en = 'Hungary' WHERE code = 'HU';
UPDATE countries SET name_en = 'Indonesia' WHERE code = 'ID';
UPDATE countries SET name_en = 'Ireland' WHERE code = 'IE';
UPDATE countries SET name_en = 'Israel' WHERE code = 'IL';
UPDATE countries SET name_en = 'Isle of Man' WHERE code = 'IM';
UPDATE countries SET name_en = 'India' WHERE code = 'IN';
UPDATE countries SET name_en = 'Iraq' WHERE code = 'IQ';
UPDATE countries SET name_en = 'Iran' WHERE code = 'IR';
UPDATE countries SET name_en = 'Iceland' WHERE code = 'IS';
UPDATE countries SET name_en = 'Italy' WHERE code = 'IT';
UPDATE countries SET name_en = 'Jersey' WHERE code = 'JE';
UPDATE countries SET name_en = 'Jamaica' WHERE code = 'JM';
UPDATE countries SET name_en = 'Jordan' WHERE code = 'JO';
UPDATE countries SET name_en = 'Japan' WHERE code = 'JP';
UPDATE countries SET name_en = 'Kenya' WHERE code = 'KE';
UPDATE countries SET name_en = 'Kyrgyzstan' WHERE code = 'KG';
UPDATE countries SET name_en = 'Cambodia' WHERE code = 'KH';
UPDATE countries SET name_en = 'Kiribati' WHERE code = 'KI';
UPDATE countries SET name_en = 'Comoros' WHERE code = 'KM';
UPDATE countries SET name_en = 'Saint Kitts and Nevis' WHERE code = 'KN';
UPDATE countries SET name_en = 'North Korea' WHERE code = 'KP';
UPDATE countries SET name_en = 'South Korea' WHERE code = 'KR';
UPDATE countries SET name_en = 'Kuwait' WHERE code = 'KW';
UPDATE countries SET name_en = 'Cayman Islands' WHERE code = 'KY';
UPDATE countries SET name_en = 'Kazakhstan' WHERE code = 'KZ';
UPDATE countries SET name_en = 'Laos' WHERE code = 'LA';
UPDATE countries SET name_en = 'Lebanon' WHERE code = 'LB';
UPDATE countries SET name_en = 'Saint Lucia' WHERE code = 'LC';
UPDATE countries SET name_en = 'Liechtenstein' WHERE code = 'LI';
UPDATE countries SET name_en = 'Liberia' WHERE code = 'LR';
UPDATE countries SET name_en = 'Lesotho' WHERE code = 'LS';
UPDATE countries SET name_en = 'Lithuania' WHERE code = 'LT';
UPDATE countries SET name_en = 'Luxembourg' WHERE code = 'LU';
UPDATE countries SET name_en = 'Latvia' WHERE code = 'LV';
UPDATE countries SET name_en = 'Libya' WHERE code = 'LY';
UPDATE countries SET name_en = 'Morocco' WHERE code = 'MA';
UPDATE countries SET name_en = 'Monaco' WHERE code = 'MC';
UPDATE countries SET name_en = 'Moldova' WHERE code = 'MD';
UPDATE countries SET name_en = 'Montenegro' WHERE code = 'ME';
UPDATE countries SET name_en = 'Madagascar' WHERE code = 'MG';
UPDATE countries SET name_en = 'Marshall Islands' WHERE code = 'MH';
UPDATE countries SET name_en = 'North Macedonia' WHERE code = 'MK';
UPDATE countries SET name_en = 'Mali' WHERE code = 'ML';
UPDATE countries SET name_en = 'Myanmar' WHERE code = 'MM';
UPDATE countries SET name_en = 'Mongolia' WHERE code = 'MN';
UPDATE countries SET name_en = 'Macao' WHERE code = 'MO';
UPDATE countries SET name_en = 'Martinique' WHERE code = 'MQ';
UPDATE countries SET name_en = 'Mauritania' WHERE code = 'MR';
UPDATE countries SET name_en = 'Malta' WHERE code = 'MT';
UPDATE countries SET name_en = 'Mauritius' WHERE code = 'MU';
UPDATE countries SET name_en = 'Maldives' WHERE code = 'MV';
UPDATE countries SET name_en = 'Malawi' WHERE code = 'MW';
UPDATE countries SET name_en = 'Mexico' WHERE code = 'MX';
UPDATE countries SET name_en = 'Malaysia' WHERE code = 'MY';
UPDATE countries SET name_en = 'Mozambique' WHERE code = 'MZ';
UPDATE countries SET name_en = 'Namibia' WHERE code = 'NA';
UPDATE countries SET name_en = 'New Caledonia' WHERE code = 'NC';
UPDATE countries SET name_en = 'Niger' WHERE code = 'NE';
UPDATE countries SET name_en = 'Nigeria' WHERE code = 'NG';
UPDATE countries SET name_en = 'Nicaragua' WHERE code = 'NI';
UPDATE countries SET name_en = 'Netherlands' WHERE code = 'NL';
UPDATE countries SET name_en = 'Norway' WHERE code = 'NO';
UPDATE countries SET name_en = 'Nepal' WHERE code = 'NP';
UPDATE countries SET name_en = 'Nauru' WHERE code = 'NR';
UPDATE countries SET name_en = 'New Zealand' WHERE code = 'NZ';
UPDATE countries SET name_en = 'Oman' WHERE code = 'OM';
UPDATE countries SET name_en = 'Panama' WHERE code = 'PA';
UPDATE countries SET name_en = 'Peru' WHERE code = 'PE';
UPDATE countries SET name_en = 'French Polynesia' WHERE code = 'PF';
UPDATE countries SET name_en = 'Papua New Guinea' WHERE code = 'PG';
UPDATE countries SET name_en = 'Philippines' WHERE code = 'PH';
UPDATE countries SET name_en = 'Pakistan' WHERE code = 'PK';
UPDATE countries SET name_en = 'Poland' WHERE code = 'PL';
UPDATE countries SET name_en = 'Puerto Rico' WHERE code = 'PR';
UPDATE countries SET name_en = 'Palestine' WHERE code = 'PS';
UPDATE countries SET name_en = 'Portugal' WHERE code = 'PT';
UPDATE countries SET name_en = 'Palau' WHERE code = 'PW';
UPDATE countries SET name_en = 'Paraguay' WHERE code = 'PY';
UPDATE countries SET name_en = 'Qatar' WHERE code = 'QA';
UPDATE countries SET name_en = 'Reunion' WHERE code = 'RE';
UPDATE countries SET name_en = 'Romania' WHERE code = 'RO';
UPDATE countries SET name_en = 'Serbia' WHERE code = 'RS';
UPDATE countries SET name_en = 'Russia' WHERE code = 'RU';
UPDATE countries SET name_en = 'Rwanda' WHERE code = 'RW';
UPDATE countries SET name_en = 'Saudi Arabia' WHERE code = 'SA';
UPDATE countries SET name_en = 'Solomon Islands' WHERE code = 'SB';
UPDATE countries SET name_en = 'Seychelles' WHERE code = 'SC';
UPDATE countries SET name_en = 'Sudan' WHERE code = 'SD';
UPDATE countries SET name_en = 'Sweden' WHERE code = 'SE';
UPDATE countries SET name_en = 'Singapore' WHERE code = 'SG';
UPDATE countries SET name_en = 'Slovenia' WHERE code = 'SI';
UPDATE countries SET name_en = 'Slovakia' WHERE code = 'SK';
UPDATE countries SET name_en = 'Sierra Leone' WHERE code = 'SL';
UPDATE countries SET name_en = 'San Marino' WHERE code = 'SM';
UPDATE countries SET name_en = 'Senegal' WHERE code = 'SN';
UPDATE countries SET name_en = 'Somalia' WHERE code = 'SO';
UPDATE countries SET name_en = 'Suriname' WHERE code = 'SR';
UPDATE countries SET name_en = 'South Sudan' WHERE code = 'SS';
UPDATE countries SET name_en = 'Sao Tome and Principe' WHERE code = 'ST';
UPDATE countries SET name_en = 'El Salvador' WHERE code = 'SV';
UPDATE countries SET name_en = 'Syria' WHERE code = 'SY';
UPDATE countries SET name_en = 'Eswatini' WHERE code = 'SZ';
UPDATE countries SET name_en = 'Chad' WHERE code = 'TD';
UPDATE countries SET name_en = 'Togo' WHERE code = 'TG';
UPDATE countries SET name_en = 'Thailand' WHERE code = 'TH';
UPDATE countries SET name_en = 'Tajikistan' WHERE code = 'TJ';
UPDATE countries SET name_en = 'Timor-Leste' WHERE code = 'TL';
UPDATE countries SET name_en = 'Turkmenistan' WHERE code = 'TM';
UPDATE countries SET name_en = 'Tunisia' WHERE code = 'TN';
UPDATE countries SET name_en = 'Tonga' WHERE code = 'TO';
UPDATE countries SET name_en = 'Turkey' WHERE code = 'TR';
UPDATE countries SET name_en = 'Trinidad and Tobago' WHERE code = 'TT';
UPDATE countries SET name_en = 'Tuvalu' WHERE code = 'TV';
UPDATE countries SET name_en = 'Taiwan' WHERE code = 'TW';
UPDATE countries SET name_en = 'Tanzania' WHERE code = 'TZ';
UPDATE countries SET name_en = 'Ukraine' WHERE code = 'UA';
UPDATE countries SET name_en = 'Uganda' WHERE code = 'UG';
UPDATE countries SET name_en = 'United States' WHERE code = 'US';
UPDATE countries SET name_en = 'Uruguay' WHERE code = 'UY';
UPDATE countries SET name_en = 'Uzbekistan' WHERE code = 'UZ';
UPDATE countries SET name_en = 'Vatican City' WHERE code = 'VA';
UPDATE countries SET name_en = 'Saint Vincent and the Grenadines' WHERE code = 'VC';
UPDATE countries SET name_en = 'Venezuela' WHERE code = 'VE';
UPDATE countries SET name_en = 'U.S. Virgin Islands' WHERE code = 'VI';
UPDATE countries SET name_en = 'Vietnam' WHERE code = 'VN';
UPDATE countries SET name_en = 'Vanuatu' WHERE code = 'VU';
UPDATE countries SET name_en = 'Samoa' WHERE code = 'WS';
UPDATE countries SET name_en = 'Kosovo' WHERE code = 'XK';
UPDATE countries SET name_en = 'Yemen' WHERE code = 'YE';
UPDATE countries SET name_en = 'Mayotte' WHERE code = 'YT';
UPDATE countries SET name_en = 'South Africa' WHERE code = 'ZA';
UPDATE countries SET name_en = 'Zambia' WHERE code = 'ZM';
UPDATE countries SET name_en = 'Zimbabwe' WHERE code = 'ZW';

COMMIT;
