-- VitalGo Countries Data Export
-- Generated: 2025-11-20 10:45:13
-- Total Records: 221 countries

-- Table structure for countries
CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(2) UNIQUE NOT NULL,
    flag_emoji VARCHAR(10),
    phone_code VARCHAR(10) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_countries_code ON countries(code);

-- Insert countries data
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (1, 'Colombia', 'CO', '🇨🇴', '+57', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (2, 'Venezuela', 'VE', '🇻🇪', '+58', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (3, 'Ecuador', 'EC', '🇪🇨', '+593', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (4, 'Perú', 'PE', '🇵🇪', '+51', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (5, 'Brasil', 'BR', '🇧🇷', '+55', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (6, 'Panamá', 'PA', '🇵🇦', '+507', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (7, 'Costa Rica', 'CR', '🇨🇷', '+506', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (8, 'Nicaragua', 'NI', '🇳🇮', '+505', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (9, 'Honduras', 'HN', '🇭🇳', '+504', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (10, 'El Salvador', 'SV', '🇸🇻', '+503', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (11, 'Guatemala', 'GT', '🇬🇹', '+502', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (12, 'Belice', 'BZ', '🇧🇿', '+501', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (13, 'Argentina', 'AR', '🇦🇷', '+54', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (14, 'Chile', 'CL', '🇨🇱', '+56', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (15, 'Uruguay', 'UY', '🇺🇾', '+598', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (16, 'Paraguay', 'PY', '🇵🇾', '+595', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (17, 'Bolivia', 'BO', '🇧🇴', '+591', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (18, 'Guyana', 'GY', '🇬🇾', '+592', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (19, 'Surinam', 'SR', '🇸🇷', '+597', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (20, 'Guayana Francesa', 'GF', '🇬🇫', '+594', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (21, 'México', 'MX', '🇲🇽', '+52', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (22, 'Estados Unidos', 'US', '🇺🇸', '+1', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (23, 'Canadá', 'CA', '🇨🇦', '+1', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (24, 'Cuba', 'CU', '🇨🇺', '+53', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (25, 'República Dominicana', 'DO', '🇩🇴', '+1-809', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (26, 'Haití', 'HT', '🇭🇹', '+509', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (27, 'Jamaica', 'JM', '🇯🇲', '+1-876', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (28, 'Puerto Rico', 'PR', '🇵🇷', '+1-787', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (29, 'Trinidad y Tobago', 'TT', '🇹🇹', '+1-868', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (30, 'Bahamas', 'BS', '🇧🇸', '+1-242', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (31, 'Barbados', 'BB', '🇧🇧', '+1-246', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (32, 'España', 'ES', '🇪🇸', '+34', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (33, 'Francia', 'FR', '🇫🇷', '+33', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (34, 'Italia', 'IT', '🇮🇹', '+39', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (35, 'Alemania', 'DE', '🇩🇪', '+49', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (36, 'Inglaterra', 'GB', '🇬🇧', '+44', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (37, 'Portugal', 'PT', '🇵🇹', '+351', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (38, 'Países Bajos', 'NL', '🇳🇱', '+31', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (39, 'Suiza', 'CH', '🇨🇭', '+41', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (40, 'Bélgica', 'BE', '🇧🇪', '+32', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (41, 'Suecia', 'SE', '🇸🇪', '+46', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (42, 'Noruega', 'NO', '🇳🇴', '+47', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (43, 'Dinamarca', 'DK', '🇩🇰', '+45', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (44, 'Polonia', 'PL', '🇵🇱', '+48', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (45, 'Rusia', 'RU', '🇷🇺', '+7', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (46, 'China', 'CN', '🇨🇳', '+86', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (47, 'Japón', 'JP', '🇯🇵', '+81', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (48, 'Corea del Sur', 'KR', '🇰🇷', '+82', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (49, 'India', 'IN', '🇮🇳', '+91', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (50, 'Filipinas', 'PH', '🇵🇭', '+63', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (51, 'Tailandia', 'TH', '🇹🇭', '+66', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (52, 'Vietnam', 'VN', '🇻🇳', '+84', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (53, 'Indonesia', 'ID', '🇮🇩', '+62', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (54, 'Singapur', 'SG', '🇸🇬', '+65', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (55, 'Malasia', 'MY', '🇲🇾', '+60', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (56, 'Israel', 'IL', '🇮🇱', '+972', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (57, 'Emiratos Árabes Unidos', 'AE', '🇦🇪', '+971', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (58, 'Arabia Saudita', 'SA', '🇸🇦', '+966', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (59, 'Turquía', 'TR', '🇹🇷', '+90', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (60, 'Sudáfrica', 'ZA', '🇿🇦', '+27', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (61, 'Nigeria', 'NG', '🇳🇬', '+234', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (62, 'Egipto', 'EG', '🇪🇬', '+20', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (63, 'Kenia', 'KE', '🇰🇪', '+254', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (64, 'Marruecos', 'MA', '🇲🇦', '+212', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (65, 'Argelia', 'DZ', '🇩🇿', '+213', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (66, 'Ghana', 'GH', '🇬🇭', '+233', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (67, 'Australia', 'AU', '🇦🇺', '+61', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (68, 'Nueva Zelanda', 'NZ', '🇳🇿', '+64', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (69, 'Antigua y Barbuda', 'AG', '🇦🇬', '+1-268', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (70, 'Aruba', 'AW', '🇦🇼', '+297', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (71, 'Curazao', 'CW', '🇨🇼', '+599', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (72, 'Dominica', 'DM', '🇩🇲', '+1-767', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (73, 'Granada', 'GD', '🇬🇩', '+1-473', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (74, 'Guadalupe', 'GP', '🇬🇵', '+590', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (75, 'Martinica', 'MQ', '🇲🇶', '+596', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (76, 'San Cristóbal y Nieves', 'KN', '🇰🇳', '+1-869', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (77, 'Santa Lucía', 'LC', '🇱🇨', '+1-758', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (78, 'San Vicente y las Granadinas', 'VC', '🇻🇨', '+1-784', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (79, 'Albania', 'AL', '🇦🇱', '+355', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (80, 'Andorra', 'AD', '🇦🇩', '+376', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (81, 'Armenia', 'AM', '🇦🇲', '+374', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (82, 'Austria', 'AT', '🇦🇹', '+43', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (83, 'Azerbaiyán', 'AZ', '🇦🇿', '+994', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (84, 'Bielorrusia', 'BY', '🇧🇾', '+375', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (85, 'Bosnia y Herzegovina', 'BA', '🇧🇦', '+387', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (86, 'Bulgaria', 'BG', '🇧🇬', '+359', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (87, 'Croacia', 'HR', '🇭🇷', '+385', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (88, 'Chipre', 'CY', '🇨🇾', '+357', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (89, 'República Checa', 'CZ', '🇨🇿', '+420', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (90, 'Estonia', 'EE', '🇪🇪', '+372', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (91, 'Finlandia', 'FI', '🇫🇮', '+358', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (92, 'Georgia', 'GE', '🇬🇪', '+995', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (93, 'Grecia', 'GR', '🇬🇷', '+30', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (94, 'Hungría', 'HU', '🇭🇺', '+36', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (95, 'Islandia', 'IS', '🇮🇸', '+354', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (96, 'Irlanda', 'IE', '🇮🇪', '+353', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (97, 'Kazajistán', 'KZ', '🇰🇿', '+7', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (98, 'Kosovo', 'XK', '🇽🇰', '+383', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (99, 'Letonia', 'LV', '🇱🇻', '+371', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (100, 'Liechtenstein', 'LI', '🇱🇮', '+423', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (101, 'Lituania', 'LT', '🇱🇹', '+370', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (102, 'Luxemburgo', 'LU', '🇱🇺', '+352', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (103, 'Macedonia del Norte', 'MK', '🇲🇰', '+389', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (104, 'Malta', 'MT', '🇲🇹', '+356', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (105, 'Moldavia', 'MD', '🇲🇩', '+373', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (106, 'Mónaco', 'MC', '🇲🇨', '+377', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (107, 'Montenegro', 'ME', '🇲🇪', '+382', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (108, 'Rumania', 'RO', '🇷🇴', '+40', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (109, 'San Marino', 'SM', '🇸🇲', '+378', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (110, 'Serbia', 'RS', '🇷🇸', '+381', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (111, 'Eslovaquia', 'SK', '🇸🇰', '+421', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (112, 'Eslovenia', 'SI', '🇸🇮', '+386', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (113, 'Ucrania', 'UA', '🇺🇦', '+380', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (114, 'Ciudad del Vaticano', 'VA', '🇻🇦', '+39', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (115, 'Afganistán', 'AF', '🇦🇫', '+93', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (116, 'Baréin', 'BH', '🇧🇭', '+973', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (117, 'Bangladés', 'BD', '🇧🇩', '+880', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (118, 'Bután', 'BT', '🇧🇹', '+975', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (119, 'Brunéi', 'BN', '🇧🇳', '+673', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (120, 'Camboya', 'KH', '🇰🇭', '+855', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (121, 'Corea del Norte', 'KP', '🇰🇵', '+850', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (122, 'Hong Kong', 'HK', '🇭🇰', '+852', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (123, 'Irak', 'IQ', '🇮🇶', '+964', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (124, 'Irán', 'IR', '🇮🇷', '+98', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (125, 'Jordania', 'JO', '🇯🇴', '+962', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (126, 'Kuwait', 'KW', '🇰🇼', '+965', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (127, 'Kirguistán', 'KG', '🇰🇬', '+996', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (128, 'Laos', 'LA', '🇱🇦', '+856', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (129, 'Líbano', 'LB', '🇱🇧', '+961', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (130, 'Macao', 'MO', '🇲🇴', '+853', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (131, 'Maldivas', 'MV', '🇲🇻', '+960', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (132, 'Mongolia', 'MN', '🇲🇳', '+976', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (133, 'Myanmar', 'MM', '🇲🇲', '+95', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (134, 'Nepal', 'NP', '🇳🇵', '+977', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (135, 'Omán', 'OM', '🇴🇲', '+968', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (136, 'Pakistán', 'PK', '🇵🇰', '+92', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (137, 'Palestina', 'PS', '🇵🇸', '+970', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (138, 'Catar', 'QA', '🇶🇦', '+974', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (139, 'Siria', 'SY', '🇸🇾', '+963', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (140, 'Taiwán', 'TW', '🇹🇼', '+886', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (141, 'Tayikistán', 'TJ', '🇹🇯', '+992', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (142, 'Timor Oriental', 'TL', '🇹🇱', '+670', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (143, 'Turkmenistán', 'TM', '🇹🇲', '+993', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (144, 'Uzbekistán', 'UZ', '🇺🇿', '+998', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (145, 'Yemen', 'YE', '🇾🇪', '+967', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (146, 'Angola', 'AO', '🇦🇴', '+244', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (147, 'Benín', 'BJ', '🇧🇯', '+229', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (148, 'Botsuana', 'BW', '🇧🇼', '+267', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (149, 'Burkina Faso', 'BF', '🇧🇫', '+226', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (150, 'Burundi', 'BI', '🇧🇮', '+257', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (151, 'Cabo Verde', 'CV', '🇨🇻', '+238', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (152, 'Camerún', 'CM', '🇨🇲', '+237', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (153, 'Chad', 'TD', '🇹🇩', '+235', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (154, 'Comoras', 'KM', '🇰🇲', '+269', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (155, 'Congo', 'CG', '🇨🇬', '+242', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (156, 'República Democrática del Congo', 'CD', '🇨🇩', '+243', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (157, 'Costa de Marfil', 'CI', '🇨🇮', '+225', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (158, 'Yibuti', 'DJ', '🇩🇯', '+253', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (159, 'Guinea Ecuatorial', 'GQ', '🇬🇶', '+240', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (160, 'Eritrea', 'ER', '🇪🇷', '+291', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (161, 'Etiopía', 'ET', '🇪🇹', '+251', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (162, 'Gabón', 'GA', '🇬🇦', '+241', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (163, 'Gambia', 'GM', '🇬🇲', '+220', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (164, 'Guinea', 'GN', '🇬🇳', '+224', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (165, 'Guinea-Bisáu', 'GW', '🇬🇼', '+245', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (166, 'Lesoto', 'LS', '🇱🇸', '+266', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (167, 'Liberia', 'LR', '🇱🇷', '+231', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (168, 'Libia', 'LY', '🇱🇾', '+218', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (169, 'Madagascar', 'MG', '🇲🇬', '+261', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (170, 'Malaui', 'MW', '🇲🇼', '+265', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (171, 'Malí', 'ML', '🇲🇱', '+223', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (172, 'Mauritania', 'MR', '🇲🇷', '+222', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (173, 'Mauricio', 'MU', '🇲🇺', '+230', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (174, 'Mozambique', 'MZ', '🇲🇿', '+258', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (175, 'Namibia', 'NA', '🇳🇦', '+264', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (176, 'Níger', 'NE', '🇳🇪', '+227', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (177, 'Ruanda', 'RW', '🇷🇼', '+250', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (178, 'Santo Tomé y Príncipe', 'ST', '🇸🇹', '+239', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (179, 'Senegal', 'SN', '🇸🇳', '+221', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (180, 'Seychelles', 'SC', '🇸🇨', '+248', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (181, 'Sierra Leona', 'SL', '🇸🇱', '+232', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (182, 'Somalia', 'SO', '🇸🇴', '+252', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (183, 'Sudán del Sur', 'SS', '🇸🇸', '+211', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (184, 'Sudán', 'SD', '🇸🇩', '+249', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (185, 'Suazilandia', 'SZ', '🇸🇿', '+268', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (186, 'Tanzania', 'TZ', '🇹🇿', '+255', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (187, 'Togo', 'TG', '🇹🇬', '+228', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (188, 'Túnez', 'TN', '🇹🇳', '+216', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (189, 'Uganda', 'UG', '🇺🇬', '+256', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (190, 'Zambia', 'ZM', '🇿🇲', '+260', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (191, 'Zimbabue', 'ZW', '🇿🇼', '+263', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (192, 'Fiji', 'FJ', '🇫🇯', '+679', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (193, 'Kiribati', 'KI', '🇰🇮', '+686', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (194, 'Islas Marshall', 'MH', '🇲🇭', '+692', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (195, 'Micronesia', 'FM', '🇫🇲', '+691', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (196, 'Nauru', 'NR', '🇳🇷', '+674', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (197, 'Palaos', 'PW', '🇵🇼', '+680', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (198, 'Papúa Nueva Guinea', 'PG', '🇵🇬', '+675', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (199, 'Samoa', 'WS', '🇼🇸', '+685', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (200, 'Islas Salomón', 'SB', '🇸🇧', '+677', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (201, 'Tonga', 'TO', '🇹🇴', '+676', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (202, 'Tuvalu', 'TV', '🇹🇻', '+688', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (203, 'Vanuatu', 'VU', '🇻🇺', '+678', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (204, 'Groenlandia', 'GL', '🇬🇱', '+299', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (205, 'Islas Feroe', 'FO', '🇫🇴', '+298', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (206, 'Nueva Caledonia', 'NC', '🇳🇨', '+687', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (207, 'Polinesia Francesa', 'PF', '🇵🇫', '+689', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (208, 'Reunión', 'RE', '🇷🇪', '+262', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (209, 'Mayotte', 'YT', '🇾🇹', '+262', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (210, 'Islas Vírgenes de EE.UU.', 'VI', '🇻🇮', '+1-340', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (211, 'Guam', 'GU', '🇬🇺', '+1-671', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (212, 'Samoa Americana', 'AS', '🇦🇸', '+1-684', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (213, 'Islas Caimán', 'KY', '🇰🇾', '+1-345', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (214, 'Bermudas', 'BM', '🇧🇲', '+1-441', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (215, 'Gibraltar', 'GI', '🇬🇮', '+350', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (216, 'Isla de Man', 'IM', '🇮🇲', '+44', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (217, 'Jersey', 'JE', '🇯🇪', '+44', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (218, 'Guernsey', 'GG', '🇬🇬', '+44', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (219, 'Escocia', 'XS', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', '+44', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (220, 'Gales', 'XW', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', '+44', TRUE);
INSERT INTO countries (id, name, code, flag_emoji, phone_code, is_active) VALUES (221, 'Bonaire', 'BQ', '🇧🇶', '+599', TRUE);

-- Reset sequence to continue from max ID
SELECT setval('countries_id_seq', (SELECT MAX(id) FROM countries));

-- Total records inserted: 221